// <auto-generated />
using DiscordPugBot.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DiscordPugBot.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20171123201734_Achievments")]
    partial class Achievments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("DiscordPugBot.Models.Achievements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("DiscordPugBot.Models.GameModes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.ToTable("GameModes");
                });

            modelBuilder.Entity("DiscordPugBot.Models.Maps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("DiscordPugBot.Models.Matches", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameModeId");

                    b.Property<int?>("MapId");

                    b.Property<int>("MatchState");

                    b.Property<DateTime>("PlayedDate");

                    b.Property<int>("Region");

                    b.Property<int>("TeamWinner");

                    b.HasKey("Id");

                    b.HasIndex("GameModeId");

                    b.HasIndex("MapId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("DiscordPugBot.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<long?>("DiscordId")
                        .HasColumnType("bigint(20)");

                    b.Property<int>("FatKided");

                    b.Property<string>("Info")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("LookingForTeam");

                    b.Property<int>("Loses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("0");

                    b.Property<int>("LosesAsCaptain")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<int>("PlayerHeroes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("0");

                    b.Property<double>("RatingsDeviation")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("350");

                    b.Property<double>("SkillRating")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("1500");

                    b.Property<string>("SteamId");

                    b.Property<int>("TimesLeftAPug");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(128)");

                    b.Property<double>("Volatility")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0.06");

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("0");

                    b.Property<int>("WinsAsCaptain")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiscordPugBot.Models.UsersAchievements", b =>
                {
                    b.Property<int>("AchievementId");

                    b.Property<int>("UserId");

                    b.HasKey("AchievementId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersAchievements");
                });

            modelBuilder.Entity("DiscordPugBot.Models.UsersMatchesRelation", b =>
                {
                    b.Property<int>("MatchId");

                    b.Property<int>("UserId");

                    b.Property<bool>("IsCaptain");

                    b.Property<double>("SkillRating");

                    b.Property<int>("Team");

                    b.HasKey("MatchId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersMatchesRelation");
                });

            modelBuilder.Entity("DiscordPugBot.Models.Matches", b =>
                {
                    b.HasOne("DiscordPugBot.Models.GameModes", "GameMode")
                        .WithMany()
                        .HasForeignKey("GameModeId");

                    b.HasOne("DiscordPugBot.Models.Maps", "Map")
                        .WithMany()
                        .HasForeignKey("MapId");
                });

            modelBuilder.Entity("DiscordPugBot.Models.UsersAchievements", b =>
                {
                    b.HasOne("DiscordPugBot.Models.Achievements", "Achievement")
                        .WithMany("UsersAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DiscordPugBot.Models.Users", "User")
                        .WithMany("UsersAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DiscordPugBot.Models.UsersMatchesRelation", b =>
                {
                    b.HasOne("DiscordPugBot.Models.Matches", "Match")
                        .WithMany("UserMatches")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DiscordPugBot.Models.Users", "User")
                        .WithMany("UserMatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
