//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBPugs.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LBPugs.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain 1: {0} Skill: {1}\nCaptain 2: {2} Skill: {3}.
        /// </summary>
        internal static string CaptainsWithSkill {
            get {
                return ResourceManager.GetString("CaptainsWithSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, You have already voted..
        /// </summary>
        internal static string ErrorAlreadyVotedForMap {
            get {
                return ResourceManager.GetString("ErrorAlreadyVotedForMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t pick that player..
        /// </summary>
        internal static string ErrorCantPickThatPlayer {
            get {
                return ResourceManager.GetString("ErrorCantPickThatPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}**, You can&apos;t ready up at this time.
        /// </summary>
        internal static string ErrorCantReadyUpRightNow {
            get {
                return ResourceManager.GetString("ErrorCantReadyUpRightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Invalid map number..
        /// </summary>
        internal static string ErrorInvaildMapNumber {
            get {
                return ResourceManager.GetString("ErrorInvaildMapNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}**, You can&apos;t leave since you are not in the {1} queue. {1} {2}/{3}
        ///.
        /// </summary>
        internal static string ErrorLeavePugYouareNotIn {
            get {
                return ResourceManager.GetString("ErrorLeavePugYouareNotIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Only captains can enter match results..
        /// </summary>
        internal static string ErrorOnlyCaptainsCanEnterResult {
            get {
                return ResourceManager.GetString("ErrorOnlyCaptainsCanEnterResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Only people in the pug can vote for map/gamemode..
        /// </summary>
        internal static string ErrorOnlyPeopleInThePugCanVote {
            get {
                return ResourceManager.GetString("ErrorOnlyPeopleInThePugCanVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}**, Pug is full..
        /// </summary>
        internal static string ErrorPugIsFull {
            get {
                return ResourceManager.GetString("ErrorPugIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;Win\&quot; if you team won, and \&quot;Lose\&quot; if your team lost. It&apos;s not that hard..
        /// </summary>
        internal static string ErrorResultWinnerWrong {
            get {
                return ResourceManager.GetString("ErrorResultWinnerWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamId to long..
        /// </summary>
        internal static string ErrorSteamIDToLong {
            get {
                return ResourceManager.GetString("ErrorSteamIDToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Userinfo to long..
        /// </summary>
        internal static string ErrorUserInfoToLong {
            get {
                return ResourceManager.GetString("ErrorUserInfoToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}**, Wait until they have finished picking teams on the last pug, before typing .add.
        /// </summary>
        internal static string ErrorWaitUntilTheyFinishedPicking {
            get {
                return ResourceManager.GetString("ErrorWaitUntilTheyFinishedPicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}**, Wrong region use .a &lt;na/eu/both&gt;..
        /// </summary>
        internal static string ErrorWrongRegionAdd {
            get {
                return ResourceManager.GetString("ErrorWrongRegionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}**, Wrong region use .l &lt;na/eu/both&gt;..
        /// </summary>
        internal static string ErrorWrongRegionLeave {
            get {
                return ResourceManager.GetString("ErrorWrongRegionLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you are already signed up. {1} {2}/{3} players..
        /// </summary>
        internal static string ErrorYouAreAlreadySignedUp {
            get {
                return ResourceManager.GetString("ErrorYouAreAlreadySignedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to pick..
        /// </summary>
        internal static string ErrorYouAreNotAllowedToPick {
            get {
                return ResourceManager.GetString("ErrorYouAreNotAllowedToPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not in the pug..
        /// </summary>
        internal static string ErrorYouAreNotInThePug {
            get {
                return ResourceManager.GetString("ErrorYouAreNotInThePug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone is ready, randoming captains..
        /// </summary>
        internal static string EveryoneReady {
            get {
                return ResourceManager.GetString("EveryoneReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting ended. **{0} {1} ({2})** won the vote. Match Id: **{3}**
        ///**GL HF**
        ///Captains don&apos;t forget to enter match results after the match. (.result &lt;win/lose&gt;)
        ///.
        /// </summary>
        internal static string GameModeVoteFinished {
            get {
                return ResourceManager.GetString("GameModeVoteFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Dices Pug Bot
        ///Stats Website:** http://dpl.victormoller.com/ 
        ///**To sign up for a pug write .add
        ///Commands:** 
        ///.help
        ///.status
        ///.userinfo &lt;username&gt;
        ///.setinfo &lt;info&gt;
        ///.add
        ///.remove
        ///.ready
        ///.pick &lt;player&gt;
        ///.vote &lt;map/gamemode&gt;
        ///.result &lt;win/lose/cancel&gt;
        ///.lookingforteam
        ///.top10
        ///.noteamplayers
        ///.nolifer
        ///.gamemodestats
        ///.mapstats.
        /// </summary>
        internal static string HelpInfo {
            get {
                return ResourceManager.GetString("HelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Total games played:** {0}
        ///{1}.
        /// </summary>
        internal static string InfoMapStats {
            get {
                return ResourceManager.GetString("InfoMapStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most active players:
        ///{0}.
        /// </summary>
        internal static string InfoMostActivePlayers {
            get {
                return ResourceManager.GetString("InfoMostActivePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players looking for team:
        ///{0}.
        /// </summary>
        internal static string InfoPlayersLookingForTeam {
            get {
                return ResourceManager.GetString("InfoPlayersLookingForTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top players:
        ///{0}.
        /// </summary>
        internal static string InfoTopPlayers {
            get {
                return ResourceManager.GetString("InfoTopPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Looking for team: {1}.
        /// </summary>
        internal static string LookingForTeamUpdated {
            get {
                return ResourceManager.GetString("LookingForTeamUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// Map: ** {0} ** \n**Vote for gamemode, you have {1}sec.** (.vote &lt;number&gt;)
        ///.
        /// </summary>
        internal static string MapVoteFinishedVoteForGameMode {
            get {
                return ResourceManager.GetString("MapVoteFinishedVoteForGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match finished **{0} Won!** {1} {2} ({3}) {4}
        ///{5}.
        /// </summary>
        internal static string MatchFinished {
            get {
                return ResourceManager.GetString("MatchFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///**Match: {0} {1}** Duration: {3}min
        ///.
        /// </summary>
        internal static string MatchInfo {
            get {
                return ResourceManager.GetString("MatchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** Games Played: {1}.
        /// </summary>
        internal static string NameAndGamesPlayed {
            get {
                return ResourceManager.GetString("NameAndGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** Rating: {1}.
        /// </summary>
        internal static string NameAndRating {
            get {
                return ResourceManager.GetString("NameAndRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** Skill rating: {1} (±{2}).
        /// </summary>
        internal static string NameAndSkillAndDeviation {
            get {
                return ResourceManager.GetString("NameAndSkillAndDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.pick &lt;number&gt;)
        ///.
        /// </summary>
        internal static string PickNumber {
            get {
                return ResourceManager.GetString("PickNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}**
        ///**Rating:** {1} (±{2})
        ///**Wins:** {3}
        ///**Losses:** {4}
        ///**Wins as captain:** {5}
        ///**Loses as captain:** {6}{7}
        ///**Looking for a team?:** {8}.
        /// </summary>
        internal static string PlayerFullInfo {
            get {
                return ResourceManager.GetString("PlayerFullInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** {1}/{2} players. **{3}** joined the queue.
        ///.
        /// </summary>
        internal static string PlayerJoinedTheQueue {
            get {
                return ResourceManager.GetString("PlayerJoinedTheQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}**, you have left the pug. **{1}** {2}/{3} players.
        ///.
        /// </summary>
        internal static string PlayerLeftTheQueue {
            get {
                return ResourceManager.GetString("PlayerLeftTheQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** Skill rating: {1} (±{2}) {3}.
        /// </summary>
        internal static string PlayerLongInfo {
            get {
                return ResourceManager.GetString("PlayerLongInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} turn to pick..
        /// </summary>
        internal static string PlayersTurnToPick {
            get {
                return ResourceManager.GetString("PlayersTurnToPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, voted for **{1}**..
        /// </summary>
        internal static string PlayerVotedForMap {
            get {
                return ResourceManager.GetString("PlayerVotedForMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} players ready. Write .r to ready up.
        ///.
        /// </summary>
        internal static string PleaseReadyUp {
            get {
                return ResourceManager.GetString("PleaseReadyUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Pug canceled**.
        /// </summary>
        internal static string PugCanceled {
            get {
                return ResourceManager.GetString("PugCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** Pug is now full, everyone ready up. (.ready).
        /// </summary>
        internal static string PugIsNowFull {
            get {
                return ResourceManager.GetString("PugIsNowFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing users that didn&apos;t ready up.
        ///{0}/{1} players.
        ///.
        /// </summary>
        internal static string RemovingPlayerThatIsNotReady {
            get {
                return ResourceManager.GetString("RemovingPlayerThatIsNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamId updated..
        /// </summary>
        internal static string SteamIDUpdated {
            get {
                return ResourceManager.GetString("SteamIDUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Team 1:**
        ///{0}
        ///**Team 2:**
        ///{1}.
        /// </summary>
        internal static string TeamLineups {
            get {
                return ResourceManager.GetString("TeamLineups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Userinfo updated..
        /// </summary>
        internal static string UserInfoUpdated {
            get {
                return ResourceManager.GetString("UserInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}.** {1} Rating: **{2}** {3}.
        /// </summary>
        internal static string UserPickingInfo {
            get {
                return ResourceManager.GetString("UserPickingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///**Vote for map, you have {MAP_VOTE_TIME}sec.** (.vote &lt;number&gt;)
        ///.
        /// </summary>
        internal static string VoteMap {
            get {
                return ResourceManager.GetString("VoteMap", resourceCulture);
            }
        }
    }
}
